/**
 * A DBGp client: the protocol Xdebug speaks.
 *
 * DBGp is XML over a socket, and it is inverted from every other debugger here: the
 * DEBUGGER LISTENS AND THE PROGRAM CONNECTS TO IT. Xdebug is told a host and port at
 * startup and dials out; there is nothing to attach to. That single fact decides the
 * shape of `languages/php/debug_adapter.mjs`.
 *
 * ## Framing
 *
 * Each message from the engine is `<length in ASCII digits> NUL <XML> NUL`. Each
 * command to the engine is one line terminated by a NUL, with no length prefix:
 *
 *     breakpoint_set -i 3 -t line -f file:///job/main.php -n 10\0
 *
 * ## It is request/response, with no event channel
 *
 * Unlike JDWP, nothing arrives unprompted. `run` does not return until the program
 * next stops, and the stop is that command's OWN reply, carrying `status="break"` and
 * an `<xdebug:message>` with the file and line. So there is no event callback here and
 * no interleaving to handle - but there is a rule that must not be broken: exactly one
 * command may be outstanding. A second command sent while `run` is in flight is
 * answered out of order at best.
 *
 * ## Why the XML parser is written here
 *
 * DBGp XML is machine-generated by one implementation: elements, attributes, CDATA, no
 * namespaces to resolve, no DTDs, no mixed content that matters. That is a hundred
 * lines. Pulling in a general-purpose XML parser to read it would add a dependency to
 * the set of files copied into the runtime image and loaded next to a student's
 * program, which is the same trade this project has already refused for source maps
 * and for JDWP.
 */

import net from 'node:net';

/** The five entities XML defines. Xdebug emits these and no others. */
const ENTITIES = { lt: '<', gt: '>', amp: '&', quot: '"', apos: "'" };

function decodeEntities(text) {
  return text.replace(/&(?:#(\d+)|#x([0-9a-fA-F]+)|([a-z]+));/g, (whole, dec, hex, name) => {
    if (dec) return String.fromCodePoint(Number(dec));
    if (hex) return String.fromCodePoint(Number.parseInt(hex, 16));
    return ENTITIES[name] ?? whole;
  });
}

/**
 * One parsed element: its name, its attributes, its element children, and the text of
 * its own CDATA sections.
 *
 * Text is kept per element rather than merged into the parent, because a `<property>`
 * holding a string has both a CDATA value of its own AND child `<property>` elements
 * when it is an array - and merging the two loses which is which.
 */
class Element {
  constructor(name, attrs) {
    this.name = name;
    this.attrs = attrs;
    this.children = [];
    this.text = '';
  }

  /** The first child with this tag name, searching only one level down. */
  child(name) {
    return this.children.find(element => element.name === name) ?? null;
  }

  /** Every child with this tag name, one level down. */
  all(name) {
    return this.children.filter(element => element.name === name);
  }
}

function parseAttributes(source) {
  const attrs = {};
  const pattern = /([\w:.-]+)\s*=\s*"([^"]*)"|([\w:.-]+)\s*=\s*'([^']*)'/g;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    const name = match[1] ?? match[3];
    attrs[name] = decodeEntities(match[2] ?? match[4]);
  }
  return attrs;
}

/**
 * Parse one DBGp document into an Element tree.
 *
 * Returns null rather than throwing on anything it does not understand: a debugger
 * that dies on a message shape it did not expect is worse than one that ignores it.
 */
export function parseXml(source) {
  const stack = [];
  let root = null;
  let at = 0;

  while (at < source.length) {
    const open = source.indexOf('<', at);
    if (open === -1) break;

    // Character data between elements. Only CDATA is kept (see below), because
    // Xdebug puts every value in CDATA and the rest is whitespace.
    at = open;

    if (source.startsWith('<?', at)) {
      const end = source.indexOf('?>', at);
      if (end === -1) break;
      at = end + 2;
      continue;
    }

    if (source.startsWith('<!--', at)) {
      const end = source.indexOf('-->', at);
      if (end === -1) break;
      at = end + 3;
      continue;
    }

    if (source.startsWith('<![CDATA[', at)) {
      const end = source.indexOf(']]>', at);
      if (end === -1) break;
      const current = stack[stack.length - 1];
      if (current) current.text += source.slice(at + 9, end);
      at = end + 3;
      continue;
    }

    if (source.startsWith('</', at)) {
      const end = source.indexOf('>', at);
      if (end === -1) break;
      stack.pop();
      at = end + 1;
      continue;
    }

    const end = source.indexOf('>', at);
    if (end === -1) break;
    const inner = source.slice(at + 1, end);
    const selfClosing = inner.endsWith('/');
    const body = selfClosing ? inner.slice(0, -1) : inner;

    const nameMatch = /^([\w:.-]+)/.exec(body);
    if (!nameMatch) return null;

    const element = new Element(nameMatch[1], parseAttributes(body.slice(nameMatch[1].length)));
    const parent = stack[stack.length - 1];
    if (parent) parent.children.push(element);
    else if (!root) root = element;

    if (!selfClosing) stack.push(element);
    at = end + 1;
  }

  return root;
}

/**
 * A DBGp session with one engine.
 *
 * Created by `DbgpListener` when the engine connects; there is no `connect()` here
 * because the direction is the other way round.
 */
export class DbgpSession {
  #socket;
  #buffer = Buffer.alloc(0);
  #queue = [];
  #waiters = [];
  #nextId = 1;
  #closed = false;
  #inFlight = Promise.resolve();

  constructor(socket) {
    this.#socket = socket;
    socket.setNoDelay(true);
    socket.on('data', chunk => this.#consume(chunk));
    socket.on('close', () => {
      this.#closed = true;
      // Anything still waiting would otherwise wait forever.
      for (const waiter of this.#waiters) waiter(null);
      this.#waiters = [];
    });
    socket.on('error', () => { this.#closed = true; });
  }

  get closed() {
    return this.#closed;
  }

  #consume(chunk) {
    this.#buffer = Buffer.concat([this.#buffer, chunk]);

    for (;;) {
      const nul = this.#buffer.indexOf(0);
      if (nul === -1) return;

      const length = Number.parseInt(this.#buffer.subarray(0, nul).toString('ascii'), 10);
      if (!Number.isFinite(length) || length < 0) {
        // Unrecoverable: without a valid length there is no way to find the next
        // message boundary, so the stream is abandoned rather than misread.
        this.#socket.destroy();
        return;
      }

      // length + the two NULs (the one after the digits and the one after the body).
      if (this.#buffer.length < nul + 1 + length + 1) return;

      const body = this.#buffer.subarray(nul + 1, nul + 1 + length).toString('utf8');
      this.#buffer = this.#buffer.subarray(nul + 1 + length + 1);

      const document = parseXml(body);
      if (!document) continue;
      if (this.#waiters.length > 0) this.#waiters.shift()(document);
      else this.#queue.push(document);
    }
  }

  /** The next message the engine sends, or null if it disconnects first. */
  next() {
    if (this.#queue.length > 0) return Promise.resolve(this.#queue.shift());
    if (this.#closed) return Promise.resolve(null);
    return new Promise(resolve => this.#waiters.push(resolve));
  }

  /**
   * Send one command and wait for its reply.
   *
   * Serialised through `#inFlight` because DBGp allows exactly one outstanding
   * command: while `run` is waiting for the program to hit a breakpoint, a
   * `stack_get` sent alongside it does not queue - it corrupts the exchange.
   *
   * `args` is appended verbatim, and `data` (already base64) goes after `--`, which
   * must be the LAST thing on the line. Putting `-i` after it made Xdebug answer
   * every `eval` with "invalid or missing options" - the `--` swallowed it.
   */
  command(name, args = '', data = null) {
    const run = async () => {
      if (this.#closed) return null;
      const id = this.#nextId++;
      const parts = [name, `-i ${id}`];
      if (args) parts.push(args);
      if (data !== null) parts.push(`-- ${data}`);
      this.#socket.write(`${parts.join(' ')}\0`);
      return this.next();
    };

    const result = this.#inFlight.then(run, run);
    // Keep the chain alive even if one command rejects, or every later command hangs.
    this.#inFlight = result.then(() => {}, () => {});
    return result;
  }

  close() {
    try { this.#socket.destroy(); } catch { /* already gone */ }
  }
}

/** Listens for the one engine connection a debug run produces. */
export class DbgpListener {
  #server;
  #resolve;

  constructor() {
    this.#server = net.createServer(socket => {
      // One session per run. A second connection would be a second PHP process,
      // which this pipeline does not produce; refusing it is safer than replacing
      // a live session underneath the IDE.
      if (!this.#resolve) { socket.destroy(); return; }
      const resolve = this.#resolve;
      this.#resolve = null;
      resolve(new DbgpSession(socket));
    });
    this.#server.on('error', () => {});
    this.session = new Promise(resolve => { this.#resolve = resolve; });
  }

  async listen(host = '127.0.0.1') {
    await new Promise(resolve => this.#server.listen(0, host, resolve));
    return this.#server.address().port;
  }

  close() {
    try { this.#server.close(); } catch { /* already closed */ }
  }
}

/**
 * `file:///job/main.php` -> `/job/main.php`.
 *
 * Xdebug always reports a URI, never a path. Decoding matters: a directory with a
 * space arrives as `%20`, and comparing the raw URI against a real path then fails
 * for exactly the students whose folder has a space in it.
 */
export function pathFromUri(uri) {
  if (typeof uri !== 'string') return '';
  const withoutScheme = uri.replace(/^file:\/\//, '');
  try {
    return decodeURIComponent(withoutScheme);
  } catch {
    return withoutScheme;
  }
}

/** `/job/main.php` -> `file:///job/main.php`, with each segment escaped. */
export function uriFromPath(filePath) {
  const normalised = String(filePath).replace(/\\/g, '/');
  const withLeadingSlash = normalised.startsWith('/') ? normalised : `/${normalised}`;
  return `file://${withLeadingSlash.split('/').map(encodeURIComponent).join('/')}`;
}

/*
 * The workspace boundary is shared, and it does not live in the adapter.
 *
 * `debug_adapter.mjs` opens a socket the moment it is imported, so a unit test cannot
 * load it - which meant the containment check could only be exercised through the
 * contract suite, against real Xdebug. That turned out to prove nothing: PHP's own
 * `open_basedir` is set to the same directory, so a traversal was refused by the
 * INTERPRETER whether or not the adapter checked at all. The test passed with the
 * check deleted.
 *
 * Re-exported from here so this module stays the one place the PHP adapter imports
 * from, and so `tests/unit/dbgp.test.mjs` keeps covering it.
 */
export { resolveInWorkspace, workspaceRelative } from '../shared/workspace-paths.mjs';
